# Course Schedule {.unnumbered}

| Week   | Date          | Topics                                                        | Readings                                                                                                                                                                  | Assignments                                                   |
|---------|-------------|-------------------|-----------------------|-------------------|
| 1      | T 8/29        | Introduction to Psychology of Language                        |                                                                                                                                                                           |                                                               |
| 1      | Th 8/31       | Science of Language                                           | Sedivy - chapter 1<br /> C&C - chapters 1-2                                                                                                                               |                                                               |
| 2      | T 9/5         | Brief Introduction to Language in the Brain                   | Sedivy - chapter 3                                                                                                                                                        |                                                               |
| 2      | Th 9/7        | Speech Perception I                                           | Sedivy - chapter 4                                                                                                                                                        | [Thought Paper Option A]{style="color:#A4036F"}               |
| 3      | T 9/12        | Speech Perception II                                          | Sedivy - chapter 7                                                                                                                                                        | [Thought Paper Option B]{style="color:#A4036F"}               |
| 3      | Th 9/14       | Words, Meaning, and Concepts I                                | C&C - chapter 3                                                                                                                                                           | Quiz 1                                                        |
| 4      | T 9/19        | Words, Meaning, and Concepts II                               | Sedivy - chapters 5 and 8                                                                                                                                                 | [Thought Paper Option C]{style="color:#A4036F"}               |
| 4      | Th 9/21       | Sentences and Syntax                                          | Sedivy - chapter 6                                                                                                                                                        | Lab Report 1                                                  |
| 5      | T 9/26        | Sentence Processing                                           | Sedivy - chapter 9                                                                                                                                                        | [Thought Paper Option D]{style="color:#A4036F"}               |
| 5      | Th 9/28       | Speaking                                                      | Sedivy - chapter 10                                                                                                                                                       | Quiz 2                                                        |
| 6      | T 10/3        | Is language innate?                                           | C&C - chapter 4-5<br /> Goldin-Meadow & Mylander (1998)                                                                                                                   | [Thought Paper Option E]{style="color:#048BA8"}               |
| 6      | Th 10/5       | Is language special to humans? Non-human animal communication | Sedivy - chapter 2<br /> C&C - chapter 7<br /> Based on groups: Herbranson (2012), Pepperberg (2002), or Ramus et al. (2000)                                              | [Thought Paper Option F]{style="color:#048BA8"}               |
| 7      | T 10/10       | Is language special to humans? Language in machines           | C&C - epilogue<br /> Kallens et al. (2023)                                                                                                                                | Lab Report 2                                                  |
| 7      | Th 10/12      | First Language Acquisition / Language Development             | Sedivy - chapter 12<br /> Based on groups: Goodluck (2010), Arunachalam & Waxman (2010), Gelman & Meyer (2011), Romberg & Saffran (2010), or Schwab & Lew-Williams (2016) | Quiz 3 <br /> [Thought Paper Option G]{style="color:#048BA8"} |
| 8      | T 10/17       | Second Language Acquisition                                   | Juffs (2010)                                                                                                                                                              | [Thought Paper Option H]{style="color:#048BA8"}               |
| 8      | Th 10/19      | Reading I                                                     | Sedivy - chapter 11                                                                                                                                                       | Final paper proposal                                          |
| 9      | T 10/24       | Reading II                                                    | Treiman (2000)                                                                                                                                                            | [Thought Paper Option I]{style="color:#12BA7C"}               |
| 9      | Th 10/26      | Language and Communication Disorders I - Aphasia              | Doedens & Meteyard (2020)                                                                                                                                                 | Lab Report 3                                                  |
| 10     | T 10/31       | Language and Communication Disorders II - Dyslexia            | Ozernov-Palchik & Gaab (2016) pages 152-162                                                                                                                               | Quiz 4                                                        |
| 10     | Th 11/2       | Election Day; Sign Language and Gesture                       | Brentari & Coppola (2013)<br /> Goldin-Meadow (2016)                                                                                                                      | [Thought Paper Option J]{style="color:#12BA7C"}               |
| 11     | T 11/6        | Language and Culture                                          | Sedivy - chapter 13<br /> C&C - chapter 6                                                                                                                                 | [Thought Paper Option K]{style="color:#12BA7C"}               |
| 11     | Th 11/9       | Language and Thought                                          | C&C - chapter 8<br /> Boroditsky (2001)<br /> January & Kako (2007)                                                                                                       | [Thought Paper Option L]{style="color:#F05D5E"}               |
| 12     | T 11/14       | Language in the Brain I                                       | Poeppel et al. (2012)                                                                                                                                                     |                                                               |
| 12     | Th 11/16      | Final paper draft peer-review (no class meeting)              |                                                                                                                                                                           | Final paper draft                                             |
| 13     | T 11/21       | Language in the Brain II                                      | Hamilton & Huth (2020)                                                                                                                                                    | Quiz 5<br />[Thought Paper Option M]{style="color:#F05D5E"}   |
| 13     | Th 11/23      | Thanksgiving Break - No Classes                               |                                                                                                                                                                           |                                                               |
| 14     | T 11/28       | Language and Music                                            | Gordon et al. (2015)<br /> Jantzen (2017)                                                                                                                                 | [Thought Paper Option N]{style="color:#F05D5E"}               |
| 14     | Th 11/30      | Presentations                                                 |                                                                                                                                                                           |                                                               |
| 15     | T 12/5        | Presentations                                                 |                                                                                                                                                                           |                                                               |
| 15     | Th 12/6       | Last day of class, Presentations                              |                                                                                                                                                                           |                                                               |
| Finals | T 12/12       | Reading Day                                                   |                                                                                                                                                                           |                                                               |
| Finals | 12/13 - 12/19 | Finals                                                        |                                                                                                                                                                           | **Final Paper**                                               |
