project:
  type: book
  output-dir: docs

book:
  title: "Psychology of Language"
  author: "Casey L. Roark"
  date: "08/05/2023"
  chapters:
    - index.qmd
    - Syllabus.qmd
    - 00-CourseSchedule.qmd
    - part: "Assignments"
      chapters:
        - LabReports.qmd
        - ThoughtPapers.qmd
        - FinalPaperPresentation.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



