project:
  type: book
  output-dir: docs

book:
  title: "Psychology of Language, Spring 2024"
  author: "Casey L. Roark"
  date: "12/27/2023"
  chapters:
    - index.qmd
    - Syllabus.qmd
    - SP24-CourseSchedule.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



