# Final paper and presentation {-}

The goal of the final paper and presentation is for you to think deeply about how we use experimental methods to answer questions about the psychology of language. You will write a paper and give a presentation that outlines a research proposal for a new experimental study about the psychology of language. 

There are four parts of this assignment: 

1. By 10/19, submit a short proposal (~1/2 a page) of a specific research question you will explore in the final paper and presentation. The proposal should detail some questions that you are interested in investigating. It should also include at least two empirical papers (outside of course materials) that you plan to read. I highly suggest you spend some time before this deadline beginning to think about this project so I can give you specific feedback and get you on the right track from the beginning.

2. By 11/16, complete a detailed outline or rough draft (~3-6 pages) of the final paper that will be peer-reviewed by a classmate and reviewed by me. This outline/draft should include the research question and any sub-questions, a detailed overview of the experimental method that you would use to answer the research question, anticipated/hypothesized results. You should cite at least five empirical sources (outside of course materials). 

3. By 11/30 (Th 11/30, T 12/5, Th 12/6), you should prepare a 5-7 minute presentation about your proposed project. You should include an introduction that lays out the purpose/question of the planned experiment, the method of the planned experiment, and the anticipated/hypothesized results. You should be prepared to answer questions about your presentation. 

4. By **TBD final date**, you should submit a final draft of the paper, incorporating feedback from the outline/draft. The paper should be at least 1500 words long (~ 6 double spaced pages in 12 pt font). You are welcome to design a follow up study to one of the studies we read about in class or choose a different topic that interests you. The paper should be in APA format. 

The paper should have the following parts:

- Abstract
- Background and significance
- Proposed experiment(s)
  - Hypothesis/hypotheses
  - Experimental design
  - Possible anticipated/hypothesized results
  - Limitations