# Course Schedule {.unnumbered}

+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| Week, Class     | Date            | Topics                                     | Readings                                                                                                                   | Assignments                                                     |
+:===============:+:===============:+:===========================================+:===========================================================================================================================+:================================================================+
| 1, 1            | T 1/23          | Introduction to Psychology of Language     | \-                                                                                                                         | Where are you now?                                              |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 1, 2            | Th 1/25         | Science of Language                        | Sedivy - chapter 1 (+RQ1)                                                                                                  | HW1                                                             |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 2, 3            | T 1/30          | Introduction to Language in the Brain      | Sedivy - chapter 3 (+RQ2)                                                                                                  | HW2<br/>                                                        |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            |                                                                                                                            | Pre-Quiz 1                                                      |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 2, 4            | Th 2/1          | Speech Perception I                        | \-                                                                                                                         | Quiz 1                                                          |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 3, 5            | T 2/6           | Speech Perception II                       | Sedivy - chapter 4 (skip 4.5), be sure to read Digging Deeper (+RQ3)                                                       | HW3                                                             |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 3, 6            | Th 2/8          | Speech Perception III                      | Sedivy - chapter 7 (+RQ4)                                                                                                  | HW4<br/>                                                        |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            |                                                                                                                            | Post-Quiz 1<br/>                                                |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            |                                                                                                                            | Pre-Quiz 2                                                      |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 4, 7            | T 2/13          | Words, Meaning, and Concepts I             | \-                                                                                                                         | Quiz 2                                                          |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 4, 8            | Th 2/15         | Words, Meaning, and Concepts II            | Sedivy - chapter 5 (+RQ5)                                                                                                  | HW5                                                             |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 5, 9            | T 2/20          | Words, Meaning, and Concepts III           | Sedivy - chapter 8 (+RQ6)                                                                                                  | HW6<br/>                                                        |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            |                                                                                                                            | Post-Quiz 2                                                     |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 5, 10           | Th 2/22         | Words, Meaning, and Concepts IV            |                                                                                                                            | HW7<br/>                                                        |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            |                                                                                                                            | Pre-Quiz 3                                                      |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 6, 11           | T 2/27          | Sentences and Syntax I                     | \-                                                                                                                         | Quiz 3                                                          |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 6, 12           | Th 2/29         | Sentences and Syntax II                    | Sedivy - chapter 6 (+RQ7)                                                                                                  | HW8                                                             |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 7, 13           | T 3/5           | Sentences and Syntax III                   |                                                                                                                            | HW9<br/>                                                        |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            |                                                                                                                            | Post-Quiz 3<br/>                                                |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 7, 14           | Th 3/7          | Sentences and Syntax IV                    | Sedivy - chapter 9 (+RQ8)                                                                                                  | Pre-Quiz 4                                                      |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 8, 15           | T 3/12          | Speaking I                                 | \-                                                                                                                         | Quiz 4                                                          |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 8, 16           | Th 3/14         | Speaking II                                | Sedivy - chapter 10 (+RQ9)                                                                                                 | HW10                                                            |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            |                                                                                                                            | Post-Quiz 4<br/>                                                |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            |                                                                                                                            | Topic choices (in class) for Special Topic Paper & Presentation |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| Spring Break, 9 | T 3/19, Th 3/21 | NO CLASS - Spring Break                    | \-                                                                                                                         |                                                                 |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 10, 17          | T 3/26          | Speaking III                               | Sedivy - chapter 11 (up to 11.2) (+RQ10)                                                                                   | Pre-Quiz 5                                                      |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 10, 18          | Th 3/28         | Is language innate? I                      |                                                                                                                            | Quiz 5                                                          |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 11, 19          | T 4/2           | Is language innate? II                     | Sedivy - chapter 2 (+RQ11)                                                                                                 |                                                                 |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            | Sedivy - chapter 13 (up to 13.3) (+RQ12)                                                                                   |                                                                 |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 11, 20          | Th 4/4          | NO CLASS due to weather                    | Everyone: Sedivy - chapter 13.3 - 13.4; The Power of Language chapter 9; (+RQ13)                                           | RR1<br/>                                                        |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            | Presenters: see Special Topics                                                                                             | Post-Quiz 5                                                     |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 12, 21          | T 4/9           | Language and Thought\                      | Everyone: (see above from cancelled class)                                                                                 | HW11<br/>                                                       |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            | Presenters: see Special Topics                                                                                             |                                                                 |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 12, 22          | Th 4/11         | Bilingualism\                              | Everyone: Sedivy - chapter 13.5 to end, chapter 9 Digging Deeper only; The Power of Language chapters 1-2; (+RQ14)         | HW12                                                            |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            | Presenters: see Special Topics                                                                                             |                                                                 |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 13, 23          | T 4/16          | Social communication & language and autism | Everyone: Sedivy - chapter 12, be sure to read Digging Deeper (+RQ15)                                                      | RR2                                                             |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            | Presenters: see Special Topics                                                                                             |                                                                 |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 13, 24          | Th 4/18         | Reading & Dyslexia                         | Everyone: Reading in the Brain (chapter 1) (+RQ16), Sedivy - ch 7 Digging Deeper only; Reading in the Brain (ch 6) (+RQ17) | RR3<br/>                                                        |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            | Presenters: see Special Topics                                                                                             | HW13                                                            |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 14, 25          | T 4/23          | Aphasia                                    | Everyone: NIDCD aphasia fact sheet, AphasiaBank Grand Rounds brief summary (+RQ18)                                         |                                                                 |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            | Presenters: see Special Topics                                                                                             |                                                                 |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 14, 26          | Th 4/25         | Gesture and Sign Language                  | Everyone: Goldin-Meadow (2017), Emmorey chapter 1 (+RQ19)                                                                  | RR4                                                             |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            | Presenters: see Special Topics                                                                                             |                                                                 |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 15, 27          | T 4/30          | Language and Music                         | Everyone: Jäncke (2012); (+RQ20)                                                                                           | RR5                                                             |
|                 |                 |                                            |                                                                                                                            |                                                                 |
|                 |                 |                                            | Presenters: see Special Topics                                                                                             |                                                                 |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| 15, 28          | Th 5/2          | Final Review                               |                                                                                                                            | Optional: Pre-final assessment                                  |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
| Finals          | T 5/14 1-3PM    | Finals                                     |                                                                                                                            | **Written Final Exam**                                          |
+-----------------+-----------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+
