# Syllabus {-}

## Course information {-}

::: {.grid .course-details}
::: {.g-col-6}
### Instructor {-}

-   {{< fa user >}}   [Dr. Casey L. Roark](www.roarklab.com)
-   {{< fa university >}}   440 McConnell Hall
-   {{< fa envelope >}}   [casey.roark\@unh.edu](mailto:casey.roark@unh.edu)
-   {{< fa brands twitter >}}   [caseyroark](https://www.twitter.com/caseyroark)
-   {{< fa calendar-check >}}   Tuesday 3-4 pm, Thursday 10-11 am, or by appointment
:::

::: {.g-col-6}
### Course details {-}

-   {{< fa caret-right >}}   PSYC 712W -- Psychology of Language
-   {{< fa check-square >}}   Pre-requisites: PSYC 402, 505, 512, 513 or permission
-   {{< fa calendar >}}   Tuesday and Thursday
-   {{< fa calendar-alt >}}   Spring 2024
-   {{< fa clock >}}   11:10 am - 12:30 pm
-   HORT 215
:::
:::

::: {.callout-note}
This syllabus is subject to change. Students will be promptly notified of any changes.
:::

## Course Overview {-}

Psychology of Language explores the cognitive and neural bases of human
language. We use language in our everyday lives mostly effortlessly and
without thinking. But underneath it all, language is extraordinarily
complex. In this course, through lectures, reading, writing, and
discussion, we will explore some of the feats and challenges of human
language including (but not limited to): 

- Components of language such as speech perception, speech production, reading, writing 
- Whether language is a uniquely human and innate ability 
- How children develop the ability to speak and understand language 
- How language functions in the brain 
- The relationship between language and thought 
- What happens when language does not function typically

## Course materials (required) {-}

-   Sedivy, J. (2014). [Language in Mind: An introduction to
    psycholinguistics](https://www.amazon.com/Language-Mind-Psycholinguistics-Julie-Sedivy/dp/1605357057). Second edition. Oxford University Press.
-   Other PDFs will be provided on the [course website](https://mycourses.unh.edu).

## Course Description {-}

Theories of language structure, functions of human language, meaning,
relationship of language to other mental processes, language
acquisition, indices of language development, speech perception,
reading.

This is a writing intensive course.

## Course Learning Objectives {-}

The overarching goal of this course is to teach you the skills and concepts that you need to critically evaluate scientific findings about the psychology of language. One of my goals is for you to take ownership over your own learning in this course to achieve the outcomes that you desire. My course is designed differently than most classes you've probably taken. The grade you achieve in this course is based on the learning objectives that you achieve and how deeply you demonstrate knowledge or mastery of the topics. More on this will follow below, but some of the possible course learning objectives are to . . . 

- Assess claims made in research articles and evaluate whether the data support or refute theories about the psychology of language
- Assess and evaluate the usefulness of different behavioral and neuroscientific methodologies to answer specific research questions
- Formulate a question about language that can be tested empirically
- Design an experiment that can address a specific research question about language
- Synthesize research findings from multiple empirical sources
- Communicate synthesized research findings in writing
- Communicate synthesized research findings orally
 
## Course Structure {-}

[myCourses/Canvas](https://mycourses.unh.edu/courses) is the learning management tool we use for this course. The
course is organized by class meetings. You will be able to find external readings and submit assignments. Please do not message me through myCourses -- email me instead.


## Grades {-}

As mentioned above, grading and assessment of your learning in this course will function differently from what you have probably encountered in your other courses. Importantly, my decisions about how grades and learning assessments will happen in this class is based on the science of learning - that is, what we know about how to actually learn and engage in the material. Because this looks different from most of what you've probably experienced before, we will spend substantial time going over what this looks like at the beginning of the semester. 

The grade you receive in this course is completely up to you. Your final grade will depend on class attendance (which is critical in this course) and completion of specific assessments of learning to a satisfactory standard. The assessments in this course are organized into modules. Achieving certain letter grades requires satisfactory completion of the different modules.

**To earn an A in this course, all of the following are required:**

1. Maximum of two unexcused absences
2. 80% or higher on all quizzes
3. 80% or higher on final exam
4. Complete Foundational Module to a satisfactory level
5. Complete Basic Module to a satisfactory level
6. Complete Module B to a satisfactory level
7. Complete Module A to a satisfactory level

**To earn a B in this course, all of the following are required:**

1. Maximum of three unexcused absences
2. 70% or higher on all quizzes
3. 70% or higher on final exam
4. Complete Foundational Module to a satisfactory level
5. Complete Basic Module to a satisfactory level
6. Complete Module B to a satisfactory level

**To earn a C in this course, all of the following are required:** 

1. Maximum of four unexcused absences
2. 60% or higher on all quizzes
3. 60% or higher on final exam
4. Complete Foundational Module to a satisfactory level
5. Complete Basic Module to a satisfactory level

**To earn a D in this course:** 

1. More than four unexcused absences
2. 60% or higher on all quizzes
3. 60% or higher on final exam
4. Complete Foundational Module to a satisfactory level

**To earn an F in this course:** 

1. More than four unexcused absences
2. <60% or higher on all quizzes
3. <60% or higher on final exam
4. Incomplete/Unsatisfactory Foundational Module 

If you are using this course to complete the Capstone requirement, you must complete the Capstone Module to a satisfactory standard. The Capstone requirement is inherently pass/fail – you either complete it to satisfactory standards or you do not. As this is independent from the other modules, you may complete the Capstone Module in addition to any other modules to receive your desired grade in the course.              

### Modules: {-}

**Foundational Module (required for A, B, C, and D)**

- During Class 1: “Where are you now?” Note – if you join this course after the first class, you still need to complete this.
- Homeworks 1-5 (must complete to satisfactory level, unlimited no-cost resubmissions)

**Basic Module (required for A, B, and C)**

- Homeworks 6-9 (must complete to satisfactory level, 2 no-cost resubmissions)
- Pre-quiz learning assessment – at least 3/5 complete  [note: this can be any three of the five options]
- Post-quiz learning assessment – at least 3/5 complete [note: this can be any three of the five options]
- Research Reports 3/5 complete [note: this can be any three of the five options]
- Reading questions 13/20 complete [note: this can be any 13 of the 20 options]

**Module B (required for A and B)**

- Homeworks 10-11 (must complete to satisfactory level, 0 no-cost resubmissions)
- Pre-quiz learning assessment – at least 4/5 complete  [note: this can be any four of the five options]
- Post-quiz learning assessment – at least 4/5 complete [note: this can be any four of the five options]
- Special Topic paper
- Research Reports 4/5 complete [note: this can be any four of the five options]
- Reading questions – 15/20 complete [note: this can be any 15 of the 20 options]

**Module A (required for A)**

- Homeworks 12-13 (must complete to satisfactory level, 0 no-cost resubmissions)
- Pre-quiz learning assessment – 5/5 complete
- Post-quiz learning assessment – 5/5 complete
- Special Topic presentation
- Special Topic paper – additional section
- Research Reports – 5/5 complete
- Reading questions – 18/20 complete [note: this can be any 18 of the 20 options]

**Capstone Module (required for taking this course to fulfill capstone requirement)**

- Fill out capstone form and submit to Psychology office
- Decide on an experiment topic and basic design – research question based on replication or extension or prior work
- Gorilla Experiment Builder: make account, complete tutorials
- Experimental Design and Analysis Plan – including variables, measures, and specific hypothesis/hypotheses
- Gorilla Experiment Builder: build your experiment
- Gorilla Experiment Builder: pilot test the entire experiment on yourself
- Gorilla Experiment Builder: work with me to run experiment
- Analyze experiment data to address your research hypothesis/question
- Plot figures of experimental results
- Discuss whether your results support/refute your hypothesis
- Integrate your findings with existing literature (Discussion)
- Motivate your research question from existing literature (Introduction)
- Summarize your methods and results in writing (Methods, Results)
- Summarize your entire experiment (question, design, results, discussion) briefly (Abstract)
- Present results of experiment at Global, Racial, and Social Inequality Lab Symposium: "Memories and Memorials" on April 19, 2024 at Great Bay Community College in Portsmouth, NH. Transportation will be provided.

**What do 'satisfactory' and 'unsatisfactory' mean?**

My goal is for you to reach your desired learning objectives (and to get the grade you hope to achieve in this class). As a result, I need to assess whether you met a learning objective or you did not meet the learning objective. 
Each assignment must be completed to satisfactory standards to be counted as complete. Unsatisfactory is the same as incomplete. There is no partial credit – an assignment either meets the standards or does not.

The requirements for a satisfactory standard will be made clear for each assignment. Examples of both satisfactory and unsatisfactory responses will be given for many assignments. If you ever are unsure of what an assignment demands for satisfactory standard, please reach out to me.
Assignments will have the possibility of resubmission (sometimes without a cost, other times with a cost - we will get into that in a sec) so that you can meet the satisfactory standards. 

It's also critical for a satisfactory standard that you turn in assignments on time. Late work may be accepted - but it will cost you (see below).

**Flexibility and tokens:**

There is built-in flexibility across the course. For the Foundational and Basic Modules, you may resubmit the assignments at no cost (unlimited times for Foundational, up to two times for Basic). For resubmissions beyond this, we will use a token system.

You will be given four (virtual) tokens at the beginning of the semester.

You may earn additional tokens in the following ways:

- turn in any Research Report at least 24 hours before the stated deadline (max 5 tokens)
- turn in the Special Topic Paper at least 24 hours before the stated deadline (1 token)
- visit my office hours (1 token per visit, max 2 tokens)
- attend the class immediately before Spring Break (3/14/24; 1 token)
- attend the last day of class (5/2/24; 1 token)

You may spend tokens in the following ways: 

- an additional resubmission attempt on any assignment (i.e., beyond two for Basic Module or any resubmission for A or B level)
- remove an unexcused absence from your total number of absences
- turn in an assignment up to 24 hours late (if you wanted to turn in an assignment 25 hours late, you'd need 2 tokens)
- drop your lowest quiz score (only once)
- If you have additional tokens at the end of the semester that you do not want to or cannot use on resubmissions, absences, or late assignments, you may spend two or three tokens to skip a question of your choice on the final exam (two tokens for short answer and drawing type questions, three tokens for essay questions). This can accumulate. If you have, let’s say, four tokens at the end of the semester, you may skip two short answer questions on the final exam. I’ll make sure you know how many tokens you have going into the final exam so you can indicate which questions you’d like to skip if relevant.
- Finally, if you have four tokens left at the end of the semester, I'll increase your grade from a B, C, or D to a B+, C+, or D+. For example, say you go into the final with six tokens. You spend two tokens to skip two questions that you’d prefer not to answer. You end the course having earned a B. With those four leftover tokens, your grade will be increased to a B+. Note that it might make more sense for you to use tokens to account for absences or to resubmit an assignment. You will not be able to use tokens to get bumped up beyond the letter grade you earned (e.g., if you earned a B, you cannot be bumped up to an A- if you have not completed the requirements for an A). Intermediate minus distinctions will not be given unless under bizarre unforeseen circumstances. If you earned a specific letter grade, you’ve earned the full letter grade (e.g., A, B, C, D).

**Unexcused versus excused absences:**

An unexcused absence is any absence that does not have a clear, documented, and reasonable reason for missing class. You may spend one of your tokens to nullify an unexcused absence.

If you must miss class for a clear, documented, and reasonable reason (e.g., sickness, medical reason, emergency, etc.), you do not need to spend one of your tokens. You must communicate with me as soon as possible with documentation, if applicable.

If you need to miss class for a planned activity, please let me know as far in advance as possible. If you need accommodation for a religious or cultural holiday/observance, you are encouraged to make the request as early in the semester as possible. 

### Assignment Types: {-}

#### Reading Questions {-}

For most classes (20/28 classes) there will be an assigned reading. There will be research questions associated with each reading that you should reflect on, answer, and identify concepts you are still struggling with or have questions about.

The reading questions are meant to give you additional examples, guidance, or ways to think about the material you are encountering. It is not meant to demonstrate the only parts of the chapter you should read or pay attention to. You may be quizzed or asked about things that are in the reading, but are not addressed in the reading questions. You are responsible for all material in the reading.

#### Homework {-}

There are several homework assignments that are due throughout the semester. Some of these are foundational for further progress in the course and are thus a part of the Foundational Module. Some of these are basic aspects that I would expect to be mastered for general C-level passing of this course and are part of the Basic Module. Others are more advanced and get into demonstration of deeper conceptual knowledge on psychology of language and are in Modules A and B.

Each assignment has its own description, which can be accessed through the course website. Take note of the specific assignments required for the completion of specific modules above.

Most homework will align with readings and the topics that are being covered in class at that time.

#### Quizzes and learning assessments {-}

There will be five quizzes associated with the first part of this course. Quizzes are designed to make sure that you are engaging with and understanding the material and will cover both readings and lectures. Quizzes will be associated with each specific topic and will not be cumulative. Quizzes will be administered in person at the end of each topic and will have multiple choice, matching, fill-in-the-blanks, true/false, and identification question formats.

Pre-quiz learning assessments. Before each quiz, you will complete a pre-quiz learning assessment. You will rate your confidence about certain topics and identify concepts you still have questions about. We will address these ongoing questions in class on the day before each quiz.

Post-quiz learning assessments. After each quiz, you will complete a post-quiz learning assessment. For each question you were incorrect, you should reflect on your thinking – why did you make the response that you did? What was incorrect about this response and what is the correct response? How will you change your behavior for the next quiz?

#### Final Exam {-}

There is a cumulative written final exam for this course. This exam will assess your knowledge acquired from topics spanning across the course. The exam grades will not be curved, but please note the relatively flexible scores to demonstrate mastery over the material (e.g., A >= 80% on final exam; B >=70% on final exam; C/D: >= 60% on final exam; F: <60% on final exam) in addition to the other module-based assignments in the course.

The final exam will occur in person on a date determined by the university’s schedule – this is not negotiable.

As stated above, you may trade in tokens to skip questions on the final, with no limit on the number of tokens (2 tokens, 1 short answer or drawing question; 3 tokens, 1 essay question). Note that you may have a possible maximum of 14 tokens. There will be 10 questions on the final, so you will still need take the final, but this will simplify it greatly if you are able to/choose to save your tokens.

#### Research Reports {-}

Five times in the semester, Research Reports will be due. Research Reports require you to read a specific brief research article, answer some basic questions about the experimental design (e.g., dependent/independent variables, measures, hypotheses), summarize the methods and results in your own words, and reflect on the meaning of the research outcomes based on what you’ve learned in the class and your real-world experiences.

#### Special Topic Paper {-}

For students who wish to demonstrate further mastery over the course materials (and earn an A or B in the course), a Special Topic Paper will be required. This topic will be one of the advanced special topics covered in the second half of the course. This paper will require thinking deeply about how research in this topic area relates to concepts we have discussed in class.

Basic requirements of a Special Topic Paper:

- Selection of special topic (with my approval)
- Read article assigned for special topic
- Submitted on time – due by the beginning of class on the day of the special topic discussion
- Fulfill specific requirements of special topic paper (defined specifically in that assignment)

“A” requirements of a Special Topic Paper:

- All Basic requirements
- Complete an additional section: based on the research, identify an outstanding research question – something that was not answered here. Design an experiment that can address this question using a method we have discussed in class or you have read about.

#### Special Topic Presentation {-}

For students who wish to demonstrate further mastery over the course materials (and earn an A in the course), a Special Topic Presentation will be required. The presentation will cover the same material as the Special Topic Paper. Students will demonstrate additional in-depth knowledge by being able to communicate their research on the special topic orally with a PowerPoint/slides presentation to their peers. They should also be expected to facilitate discussion by asking questions to their peers and also answering any questions posed during discussion.


## Course Policies

### Office hours
Please watch this video on common misconceptions about office hours:

{{< video https://vimeo.com/270014784?embedded=true&source=vimeo_logo&owner=2248721 >}}

Office hours are set times dedicated to all of you. This means that I will be in my office waiting for you to come by and talk to me with whatever questions you have. This is the best and easiest way to find me and the best chance for discussing class material and concerns. If you are not available during my regularly scheduled office hours, please email me to schedule a different time to meet. *Plus, you can earn up to two tokens by coming to see me twice during my scheduled or one-off office hours!*

### Attendance {-} 
Attending and participating in class are important parts of this course. Attendance will be taken in each class period. Participation will be assessed for each class period and students will be given multiple options for participation over the course of the semester (e.g., group discussion, pair discussion, self-reflection, in class activities, etc.). If you need to miss class for a planned activity, please let me know as far in advance as possible. If you need accommodation for a religious or cultural holiday/observance, you are encouraged to make the request as early in the semester as possible. 

If you are dealing with an unexpected, extenuating circumstance that will keep you out of class or affect your performance for more than a day or two, reach out to the Dean of Students ([dean.students@unh.edu](dean.students@unh.edu)) to request a letter be sent to all your faculty. If you are required to miss a significant class, you will be provided temporary academic supports so that you can continue to make satisfactory progress in this course. Please contact your course instructor to discuss the specific types of supports that will be implemented during your absence. 

### Late work
I would **highly recommend** staying caught up as much as possible, but if you need to turn something in late, please let me know at least 24 hours before the due date. Specific policies for late assignments are listed for individual assignments.

### Technical Requirements and Technical Support {-}
See [website listings](https://online.unh.edu/technical-requirements) for current recommendations and requirements related to this course. For technical assistance please call (603) 862-4242 or fill out an [online support form](https://itsupport.unh.edu/onlinelearning/).

### University Disability Accommodations {-}
The University is committed to providing students with documented disabilities equal access to all university programs and facilities. If you think you have a disability requiring accommodations, you must register with [Student Accessibility Services (SAS)](http://www.unh.edu/studentaccessibility) or directly contact SAS: 227 Smith Hall or sas.office@unh.edu. Accommodation letters are created by SAS with the student. Please follow-up with me privately as soon as possible to ensure timely implementation of the identified accommodations in the letter. Faculty have an obligation to respond once they receive official notice of accommodations from SAS, but are under no obligation to provide retroactive accommodations.

### Confidentiality and Mandatory Reporting of Sexual Violence or Harassment {-}
The University of New Hampshire and its faculty are committed to assuring a safe and productive educational environment for all students and for the university as a whole. To this end, **the university requires faculty members to report to the university’s [Title IX Coordinator](https://www.unh.edu/diversity-inclusion/sexual-misconduct) (Bo Zaryckyj, Bo.Zaryckyj@unh.edu, 603-862-2930/1527 TTY) any incidents of sexual violence and harassment shared by students**. If you wish to speak to a confidential support service provider who does not have this reporting responsibility because their discussions with clients are subject to legal privilege, you can contact SHARPP (Sexual Harassment & Rape Prevention Program) at (603) 862-7233/TTY (800) 735-2964. For more information about what happens when you report, how the university treats your information once a report is made to the Title IX Coordinator, your rights and reporting options at UNH (including anonymous reporting options) please visit student [reporting options](https://www.unh.edu/diversity-inclusion/sexual-misconduct/reporting-students).

Help us improve our campus and community climate. If you have observed or experienced an incident of bias, discrimination or harassment, please report the incident by contacting the Civil Rights & Equity Office at UNH.civilrights@unh.edu or (603) 862-2930 voice/ (603) 862-1527 TTY / 7-1-1 Relay NH, or visit the [CREO website](https://www.unh.edu/diversity-inclusion/civil-rights-equity-office). Anonymous reports may be submitted. 

[Lauren's Promise](https://laurenmccluskey.org/laurens-promise/). I will listen and believe you if someone is threatening you. Lauren McCluskey, a 21-year-old honors student athlete, [was murdered on October 22, 2018 by a man she briefly dated on the University of Utah campus](https://www.sltrib.com/opinion/commentary/2019/02/10/commentary-failing-lauren/). We must all take action to ensure that this never happens again. If you are in immediate danger, call 911 or UNH police ((603) 862-1427). If you are experiencing sexual assault, domestic violence, or stalking, please report it to me and I will connect you to resources or call UNH’s Psychological and Counseling Services ((603) 862-2090).

### Credit Hours {-}
This syllabus reflects the federal definition of a credit hour, which entails a minimum 3 hours of engaged time per week per credit over a 15-week semester. Examples of engaged time include class time, assignments, examinations, laboratories, participation in course-related experiences (attending a talk or performance, speakers and events, fieldwork, etc.), conferences, and office hours. Student work reflects intended learning outcomes and is verified through evidence of student achievement. For more information, please see [this document](https://www.neche.org/wp-content/uploads/2018/12/Pp111_Policy_On_Credits-And-Degrees.pdf).

### Academic Honesty {-}
Students are required to abide by the UNH Academic Honesty policy located in the [Student Rights, Rules, and Responsibilities Handbook](https://catalog.unh.edu/srrr/).   
 
Plagiarism of any type may be grounds for receiving an “F” in an assignment or an “F” in the overall course.  Plagiarism is defined as “the unattributed use of the ideas, evidence, or words of another person, or the conveying the false impression that the arguments and writing in a paper are your own.” (UNH Academic Honesty Policy, 09.3) Incidents are reported to the school dean and may be grounds for further action.  If you have questions about proper citation refer to your department’s writing guidelines.  You can contact me at any time on this issue. Additional resources can be found through the [library guides on citing sources](http://libraryguides.unh.edu/unhmcitingsources).

### Artificial Intelligence {-}
Unless otherwise specified, the use of Automated Writing Tools, including ChatGPT and similar artificial intelligence (AI) tools, is strictly prohibited in this course, even when properly attributed. The use of automated writing tools is considered plagiarism (as defined by [UNH’s Academic Integrity Policy](https://catalog.unh.edu/srrr/university-policies-regulations/academic-integrity/)) and will be handled in accordance with the existing policy: "Use or submission of intellectual property, ideas, evidence produced by another person, including computer generated text or work outsourced to third-parties, in whole or in part as one's own in any academic assessment without providing proper citation or attribution. In some cases, reusing one’s own previous work without acknowledging or citing the original work can constitute self-plagiarism."

### NameCoach {-}
We have a new tool in Canvas, NameCoach, that will help us all to pronounce each other’s names properly.  Please join me in making our learning environment as inclusive as possible by recording your name (instructions [here](https://td.unh.edu/TDClient/60/Portal/KB/ArticleDet?ID=4648)) and taking advantage of the opportunity to respectfully learn how to pronounce each other’s names.

### Curtailed Operations {-} 
If the university curtails operations due to weather, we will not hold in-person activities for our safety and the safety of others. As soon as possible, I will post an announcement on Canvas about due dates, any make-up work, and (if applicable) any online options that may make sense depending on where we are in the course.  Please make sure you have access to the UNH Alert RAVE system. If needed, sign up for RAVE Alerts [here](https://www.getrave.com/login/unh).

### Expectations {-}

The following guidelines will create a comfortable and productive learning environment throughout the semester.

You can expect me to: 

- Respect you as individuals
- Give timely feedback
- Assign work that meets the learning objectives of the course
- Adhere to the time expectations for a 4 credit course
- Give assessments that accurately reflect the material covered in class
- Provide clear and timely expectations for course requirements
- Reply to emails within 24-48 hours on weekdays

I expect you to: 

- Be attentive and engaged
- Come to class ready to participate (having done the readings)
- Adhere to the highest level of academic integrity
- Spend an adequate amount of time studying course materials each week so you can identify where you need clarification early in the learning process
- Seek help when appropriate
- Communicate with me about challenges

## General well-being and stress

Do your best to follow guidelines to keep physically healthy. Do your best to maintain a healthy lifestyle this semester by eating well, exercising, avoiding drugs and alcohol, getting enough sleep and taking some time to relax. This will help you achieve your goals and cope with stress.

All of us benefit from support during times of struggle. You are not alone. There are many helpful resources available on campus and an important part of the college experience is learning how to ask for help. Asking for support sooner rather than later is often helpful. It is courageous to reach out for help.

If you or anyone you know experiences any academic stress, difficult life events, or feelings like anxiety or depression, we strongly encourage you to seek support. [Psychological and Counseling Services (PACS)](https://www.unh.edu/pacs/) is here to help, (603) 862-2090. Consider reaching out to a friend, faculty or family member you trust for help getting connected to the support that can help. Your instructor can point you to resources.

If you or someone you know is feeling suicidal or in danger of self-harm, call someone immediately, day or night you can contact Rapid Response Access Point at 833-710-6477 or visit NH988.com. If the situation is life threatening, call the police. (UNH Police: (603) 862-1427; Off campus: 911).

If you or someone you know is experiencing food insecurity -- worry about affording food -- there are campus resources to help. Fill out a [Swipe it Forward request form](https://cm.maxient.com/reportingform.php?UnivofNH&layout_id=15) or visit the Cats' Cupboard in the MUB 140A. See this [website](https://www.unh.edu/dean-of-students/getting-help/housing-food-financial-basic-needs-support) for more Basic Needs Support and Resources. 

## General resources {-}

[Important Information about UNH Policies and Procedures for Students](https://td.unh.edu/TDClient/60/Portal/KB/ArticleDet?ID=1368)

Follow this link to view the UNH Academic Calendar that includes important dates for students and faculty including holidays and observances important to members of the UNH community: [UNH Academic Calendar](https://calendar.unh.edu//MasterCalendar.aspx?data=f1bM4GJyEC7OAZpRGWNxSrbbl6srt42DbygweOCcQCqXBA2URBJ7CdAOl8d5H3633QULXnJ%2faAyyr%2b0jnNFEvyvAYm9vn8bVYbr%2fGq1YY%2fvt%2f6p2cwrqcxdBIjjKw8NKEKDCfXgh49P2%2fDKyCjbzmm2DUp3AZkcy47t9pGdy2WMAMSzjLHAq7ZTMUfF67KnmQhLAc4DhDAEdHOkT935E6wO%2fL4IhRpjd)

### Center for Academic Resources (CFAR) {-}
Center for Academic Resources (CFAR) is where students go to improve their study skills, time management, and understanding of UNH’s academic culture. Our [professional educational counselors](https://www.unh.edu/student-success/center-academic-resources/meet-staff) and [peer academic mentors](https://www.unh.edu/student-success/center-academic-resources/resources/working-academic-mentor) work within students’ course materials to demonstrate best practices for learning concepts and preparing for exams. Find an appointment with an academic mentor of your choice on the CFAR calendar at https://unh.mywconline.com(https://unh.mywconline.com). To talk with a professional educational counselor, email us at [unh.cfar@unh.edu](unh.cfar@unh.edu), use Chat Live on our website at [https://www.unh.edu/cfar](https://www.unh.edu/cfar), or stop by Smith Hall Second floor, Monday-Friday from 8:00-4:30. The CFAR website also has a large selection of [study tips and tools](https://www.unh.edu/student-success/center-academic-resources).

### Knack {-}
Knack is a Peer-to-Peer tutoring platform that is available to all enrolled students for all undergraduate courses in Durham at no cost to students. Students looking for additional assistance outside of the classroom are advised to consider working with a peer tutor through Knack. UNH has partnered with Knack to provide students with access to verified tutors who have successfully completed this course. To view available tutors, visit [unh.joinknack.com](unh.joinknack.com). and sign in with your student account.

### Early Alert Progress Report {-}
The University is invested in your academic success, and myWildcatSuccess is a tool to help you, your faculty, and your advisors communicate. If a faculty member is concerned about your academic behavior or performance, they may submit an academic alert -- particularly around Week 5 (Sept. 22-Oct 1). Academic alerts are not punitive. The goal is to provide you with support and resources to support your success. If you receive an academic alert, you will receive an email to your UNH email address from my name in the format <Instructor Name> [Notification@GradesFirst.com] on behalf of <Instructor Name>. Alternately, find your Progress Reports under the Reports tab in myWildcatSuccess. To get to myWildcatSuccess, search for it under Tools in the portal [my.usnh.edu](https://my.usnh.edu/dashboard). and save it to Shortcuts.

The email will contain the concern and campus resource links to help you address the concern before it becomes a problem. Please meet with your faculty member or your advisor about the concern. The purpose of these alerts is to encourage you to visit the campus resources you need early on, so that you can get back on track for a successful semester. 


