# Thought Papers {-}

You must choose four options (one from each section) and complete those papers by the due date. Each paper should be at least one page (not including references) double spaced with 12-point font. 

## <span style="color:#A4036F">Section 1</span>

### Due 9/7, A: Thinking about Language {-}
In the Sedivy chapter, she writes about things that people say about language that are almost certainly wrong (Table 1.1). Sedivy puts both “You can learn language by watching television” and “You can’t learn language by watching television” on this list. Doing your own research online, write about the support for both claims. Do you think you can learn language by watching television? Relevant readings: Sedivy chapter 1.

### Due 9/12, B: Speech Perception {-}
Can speech perception in noisy contexts be improved through training and practice? If yes, describe what might be a useful training paradigm. If no, explain why not. Relevant readings: Sedivy chapters 4 and 7.

### Due 9/19, C: Concepts {-}
How do our individual experiences and contexts shape our concepts? Can you think of any examples of how your own experiences or cultural background have influenced the way you understand certain concepts or categories? Relevant readings: Sedivy chapter 8.

### Due 9/26, D: Speech Production {-}
How do emotions and stress impact speech production? Give at least three examples of how different emotions influence speech production. Is emotional speech easier or harder to understand than neutral speech? Relevant readings: Sedivy chapter 9.

## <span style="color:#048BA8">Section 2</span>

### Due 10/3, E: Sentence Processing {-}
Read the Introduction section (pages 1-2) of the article by [Kinreich et al. (2017)](papers/Kinreichetal2017.pdf). Why do you think that couples would have more brain-to-brain synchrony than strangers? Do you think this would apply only to romantic couples? Why or why not? Why do you think our brains are capable of brain-to-brain synchrony? In other words, what is the advantage of having this ability? Relevant readings: Sedivy chapter 6 and 9.
 
### Due 10/5, F: Is Language Innate/Special? {-}
Based on the readings and your experience in class so far, do you think that language is an innate human ability? Give a few examples that argue for each side (language is innate and specific to humans vs. language is learned and is not specific to humans) and pick one at the end. Relevant readings: C&C chapters 4 and 5. 

### Due 10/12, G: Language Development/Language in Machines {-}
Choose a few examples from the textbook of challenges that children face in language development. Open [ChatGPT](https://chat.openai.com/) (requires Open AI account but is free), [Bard](https://bard.google.com/) (access through Google but is free), or [Bing](https://www.bing.com/?scope=web&FORM=HDRSC2) (requires Microsoft account but is free). Give prompts to these AI language tools that match childrens’ language challenges. Does the AI tool respond similarly to children? Give the response and explain why you think that the response matches or is different from children. Relevant readings: C&C chapter 7 and epilogue, Sedivy chapter 2.

### Due 10/27, H: Second Language Acquisition {-}
How does one’s first language facilitate and hinder second language acquisition? How does second language acquisition affect one’s native language? Give at least two examples of each case (facilitate, hinder, affect). Relevant readings: Sedivy chapter 12.

## <span style="color:#12BA7C">Section 3</span>

### Due 10/24, I: Reading {-}
How do digital technologies, such as e-books or online reading platforms, affect the way that readers interact with and process written texts? What are some of the advantages and disadvantages of these technologies? Give a few examples of how you might design digital reading environments to support optimal reading comprehension and learning. 

### Due 11/2, J: Language and Communication Disorders {-}
How does dyslexia affect abilities outside of reading? Does having dyslexia always make performance worse? Describe an example of something individuals with dyslexia are better or faster at than typical individuals and explain why this might be. 

### Due 11/6, K: Language and Culture {-}
Read the Introduction section (pages 1-2) of the article by [Bailey et al. (2022)](papers/Baileyetal2022.pdf). In your own words, describe the purpose and basic methodology of the study. More generally, discuss how language shapes our perceptions of gender roles and expectations. 

## <span style="color:#F05D5E">Section 4</span>

### Due 11/14, L: Language and Thought {-}
Read the short article by [Lupyan et al. (2007)](papers/Lupyanetal2007.pdf). In your own words, describe the main questions tested in the article and what the authors found. Why do you think that labels help people learn faster? If you could change the design to this study to improve learning even more, what do you think you would do? This can involve manipulating the labels, the stimuli, or something else, but be as specific as you can. Explain why you think this would help learning. 

### Due 11/21, M: Language in the Brain {-}
If you think about popular media about zombies, they vary in their motor skills (some are slow, others are very fast) and sensory abilities (some can’t see, others have super hearing), but they usually don’t vary in their language skills. Zombies don’t have language. Or do they? Using what you know about language and the brain, why might zombies appear to have language deficits? Give a reasonable explanation about how zombies do not have the capacity for language and why this might be as well as how zombies may have the capacity for language, but cannot express it and why this might be. Relevant readings: Sedivy chapter 3.

### Due 11/28, N: Language and Music {-}
Music, like language, involves a complex set of activities and mental processes. Try to generate as detailed a list as you can of the various components that go into musical and linguistic activity, going beyond those discussed in the textbook. What makes someone good at music or language? Once you’ve generated your lists, identify which of the skills that are needed for music appear to have close analogues in language. Where do you think it would be most likely that you’d see crossover in cognitive processing? Create a proposal for how you might gather evidence to support your idea of connections between music and language skills. 
