# Course Schedule {-}

| Week | Date | Topics | Readings  | Assignments |
|------|--------|-----------------|-------------------------|------------------------|
| 1 | T 8/29  | Introduction to Psychology of Language |  | |
| 1 | Th 8/31 | Science of Language | Sedivy - chapter 1<br /> C&C - chapters 1-2 | |
| 2 | T 9/5 | Brief Introduction to Language in the Brain | Sedivy - chapter 3 | |
| 2 | Th 9/7 | Speech Perception I | Sedivy - chapter 4  | Thought Paper Option A |
| 3 | T 9/12 | Speech Perception II | Sedivy - chapter 7  | Thought Paper Option B |
| 3 | Th 9/14 | Words, Meaning, and Concepts | Sedivy - chapter 5<br /> C&C - chapter 3  | Quiz 1 | 
| 4 | T 9/19 | Words, Meaning, and Concepts  | Sedivy - chapter 8 | Thought Paper Option C |
| 4 | Th 9/21 | Words, Meaning, and Concepts | Chen & Rogers (2014) |  Lab Report 1 |
| 5 | T 9/26 | Sentences and Syntax | Sedivy - chapter 6 | Quiz 2<br /> Thought Paper Option D  | 
| 5 | Th 9/28 | Sentence Processing  | Sedivy - chapter 9 |  |
| 6 | T 10/3 | Speaking  | Sedivy - chapter 10 | Quiz 3 <br />Thought Paper Option E |
| 6 | Th 10/5 | Is language innate?  | C&C - chapter 4-5<br /> Aslin & Newport (2012) <br /> Goldin-Meadow & Mylander (1998) | |
| 7 | T 10/10 | Is language special to humans? Non-human animal communication | Sedivy - chapter 2<br /> C&C - chapter 7<br /> Based on groups:  Herbranson (2012), Pepperberg (2002), or Ramus et al. (2000) | Lab Report 2 |
| 7 | Th 10/12  | Is language special to humans? Language in machines  | C&C - epilogue<br /> Kallens et al. (2023) |  Thought Paper Option F |
| 8 | T 10/17 | First Language Acquisition / Language Development | Sedivy - chapter 12<br /> Based on groups: Goodluck (2010), Arunachalam & Waxman (2010), Gelman & Meyer (2011), Romberg & Saffran (2010), or Schwab & Lew-Williams (2016) ||
| 8 | Th 10/19 | Second Language Acquisition | Juffs (2010) | Thought Paper Option G |
| 9 | T 10/24 | Reading I | Sedivy - chapter 11<br /> Treiman (2000) | Thought Paper Option H |
| 9 | Th 10/26 | Reading II | Dehaene (2009) - selected pages | Lab Report 3 |  
| 10 | T 10/31 | Language and Communication Disorders I - Aphasia | Doedens & Meteyard (2020) | Quiz 4<br /> Thought Paper Option I  |
| 10 | Th 11/2 | Language and Communication Disorders II - Dyslexia | Ozernov-Palchik & Gaab (2016) pages 152-162 ||
| 11 | T 11/6  | Election Day; Sign Language and gesture | Brentari & Coppola (2013)<br /> Goldin-Meadow (2016) | Thought Paper Option J (last option to choose what you are writing about!) | 
| 11 | Th 11/9 | Language and Culture | Sedivy - chapter 13<br /> C&C - chapter 6 ||
| 12  | T 11/14 | Language and Thought | C&C - chapter 8<br /> Boroditsky (2001)<br /> January & Kako (2007) | Thought Paper Option K (if you haven't started now -- you need to do the last 4!) |
| 12  | Th 11/16  | Language in the Brain | Poeppel et al. (2012) | Quiz 5 |
| 13  | T 11/21 | Language in the Brain II | Hamilton & Huth (2020)  | Thought Paper Option L (only 3 left!) |
| 13  | Th 11/23 | Thanksgiving Break - No Classes  | | |
| 14  | T 11/28  | Language and Music | Gordon et al. (2015)<br /> Jantzen (2017) | Thought Paper Option M (only 2 left!) | 
| 14  | Th 11/30  | Presentations | | |
| 15  | T 12/5 | Presentations | | Thought Paper Option N (only 1 left!) |
| 15  | Th 12/6  | Last day of class, Presentations  | | |
| Finals | T 12/12  | Reading Day | |  |
| Finals | 12/13 - 12/19 | Finals | | **Final Paper** |


